# Generated by Django 3.1.6 on 2021-06-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('creator_id', models.IntegerField()),
                ('exercise_name', models.CharField(max_length=100)),
                ('exercise_unit', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('plan_name', models.CharField(max_length=100)),
                ('jan_score', models.IntegerField()),
                ('feb_score', models.IntegerField()),
                ('mar_score', models.IntegerField()),
                ('apr_score', models.IntegerField()),
                ('may_score', models.IntegerField()),
                ('jun_score', models.IntegerField()),
                ('jul_score', models.IntegerField()),
                ('aug_score', models.IntegerField()),
                ('sep_score', models.IntegerField()),
                ('oct_score', models.IntegerField()),
                ('nov_score', models.IntegerField()),
                ('dec_score', models.IntegerField()),
                ('week_score', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
