# Generated by Django 3.1.6 on 2021-06-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20210613_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='fri',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='exercises',
            name='mon',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='exercises',
            name='sat',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='exercises',
            name='sun',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='exercises',
            name='thu',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='exercises',
            name='tue',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='exercises',
            name='wed',
            field=models.BooleanField(null=True),
        ),
    ]
