# Generated by Django 3.1.6 on 2021-06-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_auto_20210613_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('exercise_id', models.IntegerField()),
                ('mon', models.BooleanField(null=True)),
                ('tue', models.BooleanField(null=True)),
                ('wed', models.BooleanField(null=True)),
                ('thu', models.BooleanField(null=True)),
                ('fri', models.BooleanField(null=True)),
                ('sat', models.BooleanField(null=True)),
                ('sun', models.BooleanField(null=True)),
            ],
        ),
    ]
