# Generated by Django 3.1.6 on 2021-06-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_plans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='exercise_id',
        ),
        migrations.AddField(
            model_name='plans',
            name='creator_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='exercise_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='plan_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
