# Generated by Django 3.1.6 on 2021-06-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_auto_20210614_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='fri',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='mon',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='sat',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='sun',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='thu',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='tue',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='wed',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
