# Generated by Django 3.1.6 on 2021-06-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0007_auto_20210614_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='plan_name',
        ),
    ]
