# Generated by Django 3.1.6 on 2021-06-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0008_remove_plans_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='exercise_time',
            field=models.IntegerField(null=True),
        ),
    ]
