# Generated by Django 3.1.6 on 2021-06-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0009_plans_exercise_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='exercise_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
