# Generated by Django 3.1.6 on 2021-06-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0010_auto_20210616_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='fri',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='mon',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='sat',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='sun',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='thu',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='tue',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='wed',
        ),
        migrations.AddField(
            model_name='plans',
            name='days',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
