# Generated by Django 3.1.6 on 2021-06-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0012_auto_20210617_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('day1', models.IntegerField(default=0)),
                ('day2', models.IntegerField(default=0)),
                ('day3', models.IntegerField(default=0)),
                ('day4', models.IntegerField(default=0)),
                ('day5', models.IntegerField(default=0)),
                ('day6', models.IntegerField(default=0)),
                ('day7', models.IntegerField(default=0)),
                ('day8', models.IntegerField(default=0)),
                ('day9', models.IntegerField(default=0)),
                ('day10', models.IntegerField(default=0)),
                ('day11', models.IntegerField(default=0)),
                ('day12', models.IntegerField(default=0)),
                ('day13', models.IntegerField(default=0)),
                ('day14', models.IntegerField(default=0)),
                ('day15', models.IntegerField(default=0)),
                ('day16', models.IntegerField(default=0)),
                ('day17', models.IntegerField(default=0)),
                ('day18', models.IntegerField(default=0)),
                ('day19', models.IntegerField(default=0)),
                ('day20', models.IntegerField(default=0)),
                ('day21', models.IntegerField(default=0)),
                ('day22', models.IntegerField(default=0)),
                ('day23', models.IntegerField(default=0)),
                ('day24', models.IntegerField(default=0)),
                ('day25', models.IntegerField(default=0)),
                ('day26', models.IntegerField(default=0)),
                ('day27', models.IntegerField(default=0)),
                ('day28', models.IntegerField(default=0)),
                ('day29', models.IntegerField(default=0)),
                ('day30', models.IntegerField(default=0)),
                ('day31', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='exercises',
            name='exercise_done',
            field=models.BooleanField(default=False),
        ),
    ]
