# Generated by Django 3.1.6 on 2021-06-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0013_auto_20210624_1925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Month',
        ),
    ]
