# Generated by Django 3.1.6 on 2021-06-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0014_delete_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('exercise_id', models.IntegerField()),
                ('date_today', models.DateField()),
                ('exercise_done', models.BooleanField(default=False)),
            ],
        ),
    ]
