# Generated by Django 3.1.6 on 2021-06-24 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0016_delete_userlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('exercise_id', models.IntegerField()),
                ('date_today', models.DateField()),
                ('exercise_done', models.BooleanField(default=False)),
                ('exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.exercises')),
            ],
        ),
        migrations.DeleteModel(
            name='Month',
        ),
    ]
