# Generated by Django 3.1.6 on 2021-06-24 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('track', '0018_auto_20210624_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.IntegerField()),
                ('exercise_name', models.CharField(max_length=100)),
                ('exercise_unit', models.CharField(max_length=100)),
                ('exercise_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100, null=True)),
                ('exercise_time', models.CharField(max_length=100, null=True)),
                ('creator_id', models.IntegerField(null=True)),
                ('mon', models.CharField(max_length=5, null=True)),
                ('tue', models.CharField(max_length=5, null=True)),
                ('wed', models.CharField(max_length=5, null=True)),
                ('thu', models.CharField(max_length=5, null=True)),
                ('fri', models.CharField(max_length=5, null=True)),
                ('sat', models.CharField(max_length=5, null=True)),
                ('sun', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date_today', models.DateField()),
                ('exercise_done', models.BooleanField(default=False)),
                ('exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.exercises')),
            ],
        ),
    ]
