# Generated by Django 3.1.6 on 2021-06-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0020_auto_20210624_2212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
