# Generated by Django 3.1.6 on 2021-06-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0021_delete_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('is_today', models.IntegerField()),
                ('exercise_done', models.BooleanField(default=False)),
                ('exercise_id', models.IntegerField(null=True)),
            ],
        ),
    ]
