# Generated by Django 3.1.6 on 2021-06-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0022_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
