# Generated by Django 3.1.6 on 2021-06-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0023_delete_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('today', models.DateField()),
                ('exercise_id', models.IntegerField(null=True)),
            ],
        ),
    ]
