# Generated by Django 3.1.6 on 2021-06-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0024_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date', models.DateField()),
                ('number_done', models.IntegerField(default=0)),
                ('total_number', models.IntegerField(default=0)),
            ],
        ),
    ]
